### ISSUE TITLE
Converting VFJ

### ISSUE THREAD

**Issue by thorn0** [simoncozens/babelfont#13]
Hi. I'm completely new to fonts. Trying to convert this VFJ file: https://github.com/excalidraw/virgil/blob/main/src/Virgil.vfj
```console
$ babelfont Virgil.vfj Virgil.ttf
Couldn't read Virgil.vfj: 'classes'
```
Is this a known issue?

**Comment by simoncozens** [comment]
That certainly shouldn’t happen. I’ll take a look. (That said the whole library is being overhauled anyway, so a fix may need to go in its replacement.)

**Comment by thorn0** [comment]
I see. If there is an easy workaround that can automated (like adding a simple property to the JSON), it will do for me.

**Comment by simoncozens** [comment]
I've just pushed two commits which allow this file to be read and compiled successfully. (Don't know about "correctly", but certainly successfully...)
