### ISSUE TITLE
Interpolating in parallel

### ISSUE THREAD

**Issue by behdad** [simoncozens/babelfont#17]
Here:
https://github.com/simoncozens/babelfont/blob/main/lib/babelfont/variablefont.py#L98

varLib works with any object that implements addition and multiplication. So you can give it entire numPy or other vectors to work on. For example, the gvar builder in varLib passes `GlyphCoordinates` objects to it.

**Comment by simoncozens** [comment]
Things are better in the new branch: https://github.com/simoncozens/babelfont/blob/2a0344f49bfbb8c9bd8f23a67a59cd5e16c94977/Lib/babelfont/convertors/truetype.py#L142

**Comment by behdad** [comment]
Much better. :)

The first delta is always the "DC component" ie. the default. But yeah, that's not quite documented.
