### ISSUE TITLE
[Feature request] Add support for‌ Glyphs via glyphsLib

### ISSUE THREAD

**Issue by alerque** [simoncozens/babelfont#2]
I would find this more useful it if also supported Glyphs files. Conversion between formats is much more complicated and out of scope for what I need, but being able to open and query some basics about a font using a common interface would be nice.

**Comment by simoncozens** [comment]
Agree. I'll add it to the (ever-growing) list. :-)

**Comment by behdad** [comment]
Can be closed. No?

**Comment by simoncozens** [comment]
Incidentally the next iteration will not use glyphsLib, just because pulling stuff into one set of objects and then marshalling them into another set of objects is stupid and inefficient.
