### ISSUE TITLE
circular dependencies

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [simoncozens/babelfont#20]
babelfont 3.0.0 alpha has circular dependecies
```
 * Error: circular dependencies:

(dev-python/fontFeatures-1.7.0:0/0::guru, ebuild scheduled for merge) depends on
 (dev-python/glyphtools-0.8.0:0/0::guru, ebuild scheduled for merge) (buildtime)
  (dev-python/babelfont-3.0.0_alpha8:0/0::guru, ebuild scheduled for merge) (buildtime)
   (dev-python/fontFeatures-1.7.0:0/0::guru, ebuild scheduled for merge) (buildtime)
```
noticed on gentoo overlay ::guru

**Comment by alerque** [comment]
fontFeatures is not declared as a dependency either. I assume this was found by scanning the source and seeing the import. Looking at the source to me it looks like an optional dependency behind a try guard, probably specifically because of this recursion.

**Comment by simoncozens** [comment]
FontFeatures should only need glyphtools for the shaper. Perhaps we need to put those things in `extras_require`.

**Comment by Alessandro-Barbieri** [comment]
I see it in pyproject.toml
https://github.com/simoncozens/babelfont/blob/ae52f6a70662feb24311509917dfaa3913b10dfa/pyproject.toml#L15

**Comment by simoncozens** [comment]
Babelfont needs fontFeatures, of course, so it can represent feature information in a neutral way.

**Comment by simoncozens** [comment]
FontFeatures now has minimal requirements.
