### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by alerque** [simoncozens/babelfont#3]
I don't care if the version is v0.0.1, it would just be helpful to have a release tagged so that I can build distro packages. This isn't too hard to reference by @master or @SHA in a pure Python environment, but it's kind of hard to build system tools that depend on it with no system library packages.

**Comment by simoncozens** [comment]
Let's fix #5 first so it actually works. :-)

**Comment by alerque** [comment]
I'm good with that.

**Comment by simoncozens** [comment]
OK, 0.0.2 is tagged and also on pypi.
