### ISSUE TITLE
edition2021 error

### ISSUE THREAD

**Issue by aaronbell** [simoncozens/babelfont#38]
I'm trying to build a venv with the following requirements:
```
fontmake>=2.4
fontbakery>=0.7
gftools>=0.7
ufomerge
```

During the install for `gftools`, it collects `babelfont` and thus `orjson`, which is erroring out.

```
Collecting orjson<4.0.0,>=3.5.1 (from babelfont->gftools>=0.7->-r requirements.txt (line 3))
  Using cached orjson-3.9.5.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      error: failed to parse manifest at `/private/var/folders/kk/89lsxbgd4gl5llzs9n1fkrj40000gn/T/pip-install-yvh8po1c/orjson_d35c399a9360409299724b07796866d1/Cargo.toml`
      
      Caused by:
        feature `edition2021` is required
      
        consider adding `cargo-features = ["edition2021"]` to the manifest
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/private/var/folders/kk/89lsxbgd4gl5llzs9n1fkrj40000gn/T/pip-modern-metadata-ny7br62e', '--interpreter', '/Users/aaronbell/Documents/LocalProjects/venv/bin/python3.9']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /private/var/folders/kk/89lsxbgd4gl5llzs9n1fkrj40000gn/T/pip-modern-metadata-ny7br62e --interpreter /Users/aaronbell/Documents/LocalProjects/venv/bin/python3.9`
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Have you run into this problem? I'm not sure how to address this...
Thanks!

**Comment by simoncozens** [comment]
The problem is that orjson is written in Rust, and you seem to have an old (pre-2021) version of Rust installed. Normally this would be fixed by your system automatically picking up a pre-compiled (binary) wheel, but apparently there weren't any available for your platform, so pip tried building it from source. With the "wrong" version of Rust installed, that wouldn't work.

I think the answer here is, sadly, to swap orjson for something else. It's super fast, but without reliable binary wheels available, it's just going to mess people up.

**Comment by simoncozens** [comment]
What version of Python / operating system are you running on? orjson claims that

> orjson supports CPython 3.7, 3.8, 3.9, 3.10, 3.11, and 3.12. It distributes amd64/x86_64, aarch64/armv8, arm7, POWER/ppc64le, and s390x wheels for Linux, amd64 and aarch64 wheels for macOS, and amd64 and i686/x86 wheels for Windows.

So that *should* cover basically everyone. I wonder why your pip couldn't find a binary wheel. How were you installing your venv, and do you have the latest version of pip?

**Comment by aaronbell** [comment]
Hm. You know, I'm a little embarrassed to say I'm not able to find the venv again where I ran into this issue. I'll go ahead and close it for now, and if I run into the bug again will follow up with more information!
