### ISSUE TITLE
Doesn't work with latest fontParts

### ISSUE THREAD

**Issue by alerque** [simoncozens/babelfont#5]
I can't get this to work with the latest fontParts library (0.9.2).

```
In [1]: import babelfont
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-8b8e97628075> in <module>
----> 1 import babelfont

/usr/lib/python3.8/site-packages/babelfont/__init__.py in <module>
      2 import fontTools
      3 import os
----> 4 from babelfont.otf.font import OTFont
      5 from babelfont.ttf.font import TTFont
      6

/usr/lib/python3.8/site-packages/babelfont/otf/font.py in <module>
----> 1 from fontParts.fontshell.ttf.font import TTFont,TTLayer
      2 from fontParts.fontshell.otf.glyph import OTGlyph
      3
      4 class OTLayer(TTLayer):
      5     glyphClass = OTGlyph

ModuleNotFoundError: No module named 'fontParts.fontshell.ttf'
```

I can `import fontParts.fontshell.font` but I don't have a `.ttf` or `.otf` modules there. Perhaps the API has changed? Since this project doesn't define any dependency versions I'm not sure where I should even start looking.

**Comment by simoncozens** [comment]
Looks like something didn’t get renamed when this package was rewritten from being an extension to fontparts to being its own thing.

**Comment by simoncozens** [comment]
Could you try it as of 01ca289, and if that works, I'll tag the release.

**Comment by alerque** [comment]
I confirm, with that commit I can import, open an OTF font, and fetch some info about it.
