### ISSUE TITLE
loading vertWidth

### ISSUE THREAD

**Issue by schriftgestalt** [simoncozens/babelfont#7]
https://github.com/simoncozens/babelfont/blob/9729a1c06b88aefb07ae7c9e45ec9a17771480d0/lib/babelfont/convertors/glyphs.py#L80

You should check if `layer.vertWidth` is set.

**Comment by simoncozens** [comment]
If it is set, what should I do? (`vertWidth` is not documented...)

**Comment by schriftgestalt** [comment]
it is 
> vertWidth float: Only stored if other than the default (ascender+descender)
(https://github.com/schriftgestalt/GlyphsSDK/blob/master/GlyphsFileFormat.md)

**Comment by schriftgestalt** [comment]
the documentation is updated now.
