### ISSUE TITLE
Source dist not usable

### ISSUE THREAD

**Issue by alerque** [simoncozens/babelfont#8]
I just tried to bump Arch Linux packaging to 0.4.0, which is what is on PyPi now. I ran into trouble because the setup script expects to do something with HISTORY.rst, which is not included in the source bundle.

I believe the solution to this is to [add a `MANIFEST.in` file](https://packaging.python.org/guides/using-manifest-in/):

```
include HISTORY.rs
```

There may be other files that need to be added too, but I'm having a hard time putting together a PR because the repo here on GitHub doesn't seem to correspond to the PyPi release at all. The latest tags on this repository are 0.0.2, so you haven't been tagging Git to match releases. Additionally the sources currently posted identify as 0.3.2, so it doesn't seem like the commits for 0.4.0 are even pushed yet.

I'll help fix the builds if you at least push whatever sources you currently have to work from ;-)

**Comment by alerque** [comment]
This is still an issue in v2.0.1 source tarball an PyPi:

```console
$ python setup.py build
Traceback (most recent call last):
  File "/home/caleb/projects/aur/python-bablefont/src/babelfont-2.0.1/setup.py", line 11, in 
      with open('HISTORY.rst') as history_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
```

**Comment by anthrotype** [comment]
I suggest using setuptools_scm which takes care not only of updating the version in setup.py based on the git tag, but also adds all the files under VCS to the source tarball so you don't have to maintain a separate MANIFEST.in (unless for excluding git-tracked files that for some reason you wish to exclude from the sdist)

**Comment by simoncozens** [comment]
Thanks for this; I've added setuptools_scm and tried again with 2.0.2 which should have all the files.
